# Generated by Django 5.2 on 2025-04-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("E_comm", "0002_alter_order_ordered_at_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
