# Generated by Django 5.2 on 2025-05-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("E_comm", "0005_productimage_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="arrived_city_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLACED", "Order Placed"),
                    ("ACCEPTED", "Order Accepted"),
                    ("SHIPPED", "Order Shipped"),
                    ("CITY", "Arrived in Your City"),
                    ("DELIVERED", "Successfully Delivered"),
                ],
                default="PLACED",
                max_length=20,
            ),
        ),
    ]
